use std::{
    env, fs,
    io::{self, ErrorKind, Write},
    path::{Component, Path, PathBuf},
};

#[derive(Debug)]
struct FrontendAsset {
    route_path: String,
    source_path: PathBuf,
}

fn main() {
    println!("cargo:rerun-if-env-changed=PROFILE");

    let manifest_dir = PathBuf::from(
        env::var_os("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR should be set by Cargo"),
    );
    let frontend_dist = manifest_dir.join("../frontend/dist");
    let out_dir =
        PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR should be set by Cargo build"));
    let generated_path = out_dir.join("frontend_assets.rs");

    println!("cargo:rerun-if-changed={}", frontend_dist.display());

    let profile = env::var("PROFILE").unwrap_or_default();
    let index_path = frontend_dist.join("index.html");
    if profile == "release" && !index_path.is_file() {
        panic!(
            "release builds embed the frontend, but frontend/dist/index.html was not found. \
             Run `cd ../frontend && npm run build` before `cargo build --release`."
        );
    }

    let assets = if index_path.is_file() {
        let frontend_dist = frontend_dist
            .canonicalize()
            .expect("frontend/dist should be readable");
        collect_assets(&frontend_dist).expect("frontend/dist should contain valid asset paths")
    } else {
        Vec::new()
    };

    for asset in &assets {
        println!("cargo:rerun-if-changed={}", asset.source_path.display());
    }

    write_generated_assets(&generated_path, &assets).expect("generated asset table should write");
}

fn collect_assets(root: &Path) -> io::Result<Vec<FrontendAsset>> {
    let mut assets = Vec::new();
    collect_assets_from_dir(root, root, &mut assets)?;
    assets.sort_by(|left, right| left.route_path.cmp(&right.route_path));
    Ok(assets)
}

fn collect_assets_from_dir(
    root: &Path,
    dir: &Path,
    assets: &mut Vec<FrontendAsset>,
) -> io::Result<()> {
    println!("cargo:rerun-if-changed={}", dir.display());

    for entry in fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        let file_type = entry.file_type()?;

        if file_type.is_dir() {
            collect_assets_from_dir(root, &path, assets)?;
        } else if file_type.is_file() {
            assets.push(FrontendAsset {
                route_path: route_path(root, &path)?,
                source_path: path.canonicalize()?,
            });
        }
    }

    Ok(())
}

fn route_path(root: &Path, path: &Path) -> io::Result<String> {
    let relative_path = path.strip_prefix(root).map_err(|error| {
        io::Error::new(
            ErrorKind::InvalidData,
            format!("asset path should be inside frontend/dist: {error}"),
        )
    })?;

    relative_path
        .components()
        .map(|component| match component {
            Component::Normal(part) => part.to_str().map(str::to_owned).ok_or_else(|| {
                io::Error::new(
                    ErrorKind::InvalidData,
                    "frontend asset paths must be valid UTF-8",
                )
            }),
            _ => Err(io::Error::new(
                ErrorKind::InvalidData,
                "frontend asset paths must be normal relative paths",
            )),
        })
        .collect::<io::Result<Vec<_>>>()
        .map(|parts| parts.join("/"))
}

fn write_generated_assets(path: &Path, assets: &[FrontendAsset]) -> io::Result<()> {
    let mut file = fs::File::create(path)?;

    writeln!(file, "// @generated by build.rs; do not edit.")?;
    writeln!(file, "pub(crate) struct EmbeddedAsset {{")?;
    writeln!(file, "    pub(crate) path: &'static str,")?;
    writeln!(file, "    pub(crate) contents: &'static [u8],")?;
    writeln!(file, "}}")?;
    writeln!(file)?;
    writeln!(
        file,
        "pub(crate) static EMBEDDED_FRONTEND_ASSETS: &[EmbeddedAsset] = &["
    )?;

    for asset in assets {
        let source_path = asset.source_path.to_str().ok_or_else(|| {
            io::Error::new(
                ErrorKind::InvalidData,
                "frontend asset source paths must be valid UTF-8",
            )
        })?;

        writeln!(
            file,
            "    EmbeddedAsset {{ path: {}, contents: include_bytes!({}) }},",
            rust_string_literal(&asset.route_path),
            rust_string_literal(source_path),
        )?;
    }

    writeln!(file, "];")?;

    Ok(())
}

fn rust_string_literal(value: &str) -> String {
    format!("{value:?}")
}
